// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaultX_WebAPI.Models;

#nullable disable

namespace VaultX_WebAPI.Migrations
{
    [DbContext(typeof(VaultxDbContext))]
    [Migration("20260109033021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VaultX_WebAPI.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("InternalRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("internalRole");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("joiningDate");

                    b.Property<string>("Shift")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("shift");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Userid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("PK_b9535a98350d5b26e7eb0c26af4");

                    b.HasIndex(new[] { "Userid" }, "REL_19fc098e857550a576b6b16112")
                        .IsUnique()
                        .HasFilter("([userid] IS NOT NULL)");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Guest", b =>
                {
                    b.Property<string>("GuestId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("guestId");

                    b.Property<DateTime?>("ActualArrivalTime")
                        .HasColumnType("datetime")
                        .HasColumnName("ActualArrivalTime");

                    b.Property<DateTime>("CheckoutTime")
                        .HasColumnType("datetime")
                        .HasColumnName("CheckoutTime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("Eta")
                        .HasColumnType("datetime")
                        .HasColumnName("eta");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Gender");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("guestName");

                    b.Property<string>("GuestPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("guestPhoneNumber");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("isVerified");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("qrCode");

                    b.Property<Guid?>("ResidenceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("residenceId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Userid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userid");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vehicleId");

                    b.Property<bool>("VisitCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("visitCompleted");

                    b.HasKey("GuestId")
                        .HasName("PK_a6145db6b105b373e1c1833a3ba");

                    b.HasIndex("ResidenceId");

                    b.HasIndex("Userid");

                    b.HasIndex(new[] { "VehicleId" }, "REL_cac7e9be74c70ea79eae4ac5c3")
                        .IsUnique()
                        .HasFilter("([vehicleId] IS NOT NULL)");

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Otp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiresAt");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("isUsed");

                    b.Property<string>("UserUserid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userUserid");

                    b.HasKey("Id")
                        .HasName("PK_32556d9d7b22031d7d0e1fd6723");

                    b.HasIndex(new[] { "ExpiresAt" }, "IDX_844706d729b144ed62f482ac2b");

                    b.HasIndex(new[] { "UserUserid" }, "REL_a4d3108840413c6e1ccce8ca43")
                        .IsUnique()
                        .HasFilter("([userUserid] IS NOT NULL)");

                    b.ToTable("otp", (string)null);
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Residence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("addressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("addressLine2");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approvedAt");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("approvedBy");

                    b.Property<string>("Block")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("block");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FlatNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("flatNumber");

                    b.Property<bool>("IsApprovedBySociety")
                        .HasColumnType("bit")
                        .HasColumnName("isApprovedBySociety");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("isPrimary");

                    b.Property<string>("Residence1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("flat")
                        .HasColumnName("residence");

                    b.Property<string>("ResidenceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("owned")
                        .HasColumnName("residenceType");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Userid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("PK_505bad416f6552d9481a82385bb");

                    b.HasIndex("Userid");

                    b.ToTable("residences", (string)null);
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Society", b =>
                {
                    b.Property<string>("SocietyId")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("society_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("postalCode");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("state");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("SocietyId")
                        .HasName("PK_54d022c07968203bbc2a1ccc9d8");

                    b.HasIndex(new[] { "UserId" }, "REL_3450f3eceecb321183417e8227")
                        .IsUnique()
                        .HasFilter("([user_id] IS NOT NULL)");

                    b.ToTable("societies", (string)null);
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.User", b =>
                {
                    b.Property<string>("Userid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userid");

                    b.Property<string>("Cnic")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("cnic");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("firstname");

                    b.Property<bool?>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isBlocked");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("isEmailVerified");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isVerified");

                    b.Property<string>("Lastname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("resident")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Userid")
                        .HasName("PK_37b098e31baedfa2b76e7876998");

                    b.HasIndex(new[] { "Email" }, "UQ_97672ac88f789774dd47f7c8be3")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Vehicle", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vehicleId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit")
                        .HasColumnName("isGuest");

                    b.Property<Guid?>("Residentid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("residentid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("VehicleColor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vehicleColor");

                    b.Property<string>("VehicleLicensePlateNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vehicleLicensePlateNumber");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vehicleModel");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vehicleName");

                    b.Property<string>("VehicleRFIDTagId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vehicleRFIDTagId");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vehicleType");

                    b.HasKey("VehicleId")
                        .HasName("PK_cc2bbdf57cb1356341edef83d44");

                    b.HasIndex("Residentid");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.VehicleAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("accessType");

                    b.Property<string>("GateName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("gateName");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("recordedBy");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vehicleId");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VehicleId");

                    b.ToTable("vehicle_access_logs", (string)null);
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Employee", b =>
                {
                    b.HasOne("VaultX_WebAPI.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("VaultX_WebAPI.Models.Employee", "Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_19fc098e857550a576b6b161125");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Guest", b =>
                {
                    b.HasOne("VaultX_WebAPI.Models.Residence", "Residence")
                        .WithMany("Guests")
                        .HasForeignKey("ResidenceId")
                        .HasConstraintName("FK_guests_residences_residenceId");

                    b.HasOne("VaultX_WebAPI.Models.User", "User")
                        .WithMany("Guests")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_guests_users_userid");

                    b.HasOne("VaultX_WebAPI.Models.Vehicle", "Vehicle")
                        .WithOne("Guest")
                        .HasForeignKey("VaultX_WebAPI.Models.Guest", "VehicleId")
                        .HasConstraintName("FK_guests_vehicles_vehicleId");

                    b.Navigation("Residence");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Otp", b =>
                {
                    b.HasOne("VaultX_WebAPI.Models.User", "UserUser")
                        .WithOne("Otp")
                        .HasForeignKey("VaultX_WebAPI.Models.Otp", "UserUserid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_a4d3108840413c6e1ccce8ca436");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Residence", b =>
                {
                    b.HasOne("VaultX_WebAPI.Models.User", "User")
                        .WithMany("Residences")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_d3685ad68ed3fa2fbb49d136990");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Society", b =>
                {
                    b.HasOne("VaultX_WebAPI.Models.User", "User")
                        .WithOne("Society")
                        .HasForeignKey("VaultX_WebAPI.Models.Society", "UserId")
                        .HasConstraintName("FK_3450f3eceecb321183417e8227a");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Vehicle", b =>
                {
                    b.HasOne("VaultX_WebAPI.Models.Residence", "Resident")
                        .WithMany("Vehicles")
                        .HasForeignKey("Residentid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_768cdb766dfb621e783856f55ee");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.VehicleAccessLog", b =>
                {
                    b.HasOne("VaultX_WebAPI.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_vehicle_access_logs_vehicles");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Residence", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.User", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("Guests");

                    b.Navigation("Otp");

                    b.Navigation("Residences");

                    b.Navigation("Society");
                });

            modelBuilder.Entity("VaultX_WebAPI.Models.Vehicle", b =>
                {
                    b.Navigation("Guest");
                });
#pragma warning restore 612, 618
        }
    }
}
